# Generated by Django 4.0.3 on 2022-03-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='generator',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='generator',
            name='validity_date',
            field=models.DateField(),
        ),
    ]
