# Generated by Django 4.0.3 on 2022-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd', '0002_remove_generator_creation_date_alter_generator_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
