# Generated by Django 4.0.3 on 2022-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd', '0004_alter_generator_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
