# Generated by Django 4.0.3 on 2022-03-29 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd', '0005_alter_generator_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='sixmonths',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generator',
            name='twelvemonths',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='validity_date',
            field=models.DateField(default=datetime.date(2022, 9, 25)),
        ),
    ]
