# Generated by Django 4.0.3 on 2022-03-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd', '0006_generator_sixmonths_generator_twelvemonths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
