# Generated by Django 4.0.3 on 2022-03-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd', '0008_generator_caracteres_generator_chiffres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='caracteres',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generator',
            name='pwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
